# Generated by Django 4.2.12 on 2024-05-29 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_auto_20200801_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('model1', 'Land Rover Series I'), ('model2', 'Land Rover Series II'), ('model3', 'Land Rover Series IIA'), ('model4', 'Land Rover Series III'), ('model5', 'Land Rover Defender 90'), ('model6', 'Land Rover Defender 110'), ('model7', 'Land Rover Defender 130'), ('model8', 'Land Rover Discovery'), ('model9', 'Land Rover Discovery Sport'), ('model10', 'Land Rover Freelander'), ('model11', 'Range Rover SE'), ('model12', 'Range Rover HSE'), ('model13', 'Range Rover Autobiography'), ('model14', 'Range Rover SVAAutobiography'), ('model15', 'Range Rover Sport SE'), ('model16', 'Range Rover Sport HSE'), ('model17', 'Range Rover Sport SVR'), ('model18', 'Range Rover Sport AutoBiography'), ('model19', 'Range Rover Evoque'), ('model20', 'Range Rover Velar')], max_length=100)),
                ('number_of_doors', models.IntegerField(choices=[(3, '3 doors'), (5, '5 doors')])),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid')], max_length=10)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.vehicle')),
            ],
            options={
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
